### ISSUE TITLE
Feature Request: Update URL with file path.

### ISSUE THREAD

**Issue by joshuapinter** [chiefpansancolt/simplecov-tailwindcss#11]
For example, if I'm looking at `coverage/index.html` and I open up the `to_do.rb` file to see the coverage, I would like the URL to be updated to reflect the specific file that I'm looking at. Something like `coverage/index.html#specs/models/to_do.rb`.

This would allow two main things: 

1. A history so you can go back on the browser to previous files, etc.
2. Reload the page after re-running the specs for that file and see the updated coverage. 

Thoughts? 

p.s. Thanks for this formatter. It's a vast improvement over the default HTML one.

**Comment by chiefpansancolt** [comment]
@joshuapinter I like the idea, I'd have to do some research on how to make that work within a single page app with no architecture behind it. presently I am working on updating the UX to be a little bit cleaner with some new tailwind items that were released. I will explore this during or after that update. Again thank you for using and enjoying this :)

**Comment by joshuapinter** [comment]
@chiefpansancolt Thanks for the reply! Do you want me to take a crack at it first?

**Comment by chiefpansancolt** [comment]
Absolutely take a crack on main branch and then I can take that and morph into new view when finished!

**Comment by joshuapinter** [comment]
Sound good! I'll try and keep it as minimal as possible. Just a push of the file path to the browser url to retain the current file and history.

It would also be nice to have it remember your position on the page but that'll be gravy.

I'll let you know how it goes.

**Comment by joshuapinter** [comment]
I started looking into this and went back to `simplecov-html` to start with a simpler environment to test with. Turns out, they are already doing this. When you open up a file it adds a `#12345...` to the URL which is the SHA1 of the file path: 

```ruby
# Return a (kind of) unique id for the source file given. Uses SHA1 on path for the id
def id(source_file)
  Digest::SHA1.hexdigest(source_file.filename)
end
```

This allows you to easily reload the coverage page and the same file you were just looking at is reloaded with the new coverage, etc.

I'm going to leave this with you for now since you're more familiar with the repo and I'm not familiar with how Stimulus JS works yet. But just wanted to give you a heads up that they're doing it in the basic HTML formatter.

Thanks!

**Comment by chiefpansancolt** [comment]
@joshuapinter ahh good catch I'll look at how to implement with stimulus to auto open based on url

**Comment by joshuapinter** [comment]
Interesting.... gonna give this overhaul another try and see how she looks! :) Thanks for keeping this updated!

**Comment by chiefpansancolt** [comment]
@joshuapinter sure thing! sorry for the long turn around on this one, life stuff, and wanted to get a ux that just worked better no matter screen size and other items. Would love feedback after you try it out!

**Comment by joshuapinter** [comment]
Just tried it out and it looks really good! And no apologies necessary. A) It's open source, and B) I get other things take priority, like kids, job, etc. :) Thanks again for following up.
