### ISSUE TITLE
[Bug]: Left hand sidebar cut off and unscrollable

### ISSUE THREAD

**Issue by mdi** [chiefpansancolt/simplecov-tailwindcss#57]
### What happened?

When having a number of groups, the left hand sidebar becomes cut off and unscrollable.

Here's the view at 100% browser magnification:

<img width="108" alt="2023-08-20_08-32-25" src="https://github.com/chiefpansancolt/simplecov-tailwindcss/assets/524808/808c8d1b-b8f8-4af4-be6d-78041389ca73">

Here's the view at 50% browser magnification:
<img width="57" alt="2023-08-20_08-37-13" src="https://github.com/chiefpansancolt/simplecov-tailwindcss/assets/524808/fe19d650-879f-45d1-b8b9-10a03f936ff4">

### Version

2.1.1

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chiefpansancolt** [comment]
Included in Version 2.2
